"""Add hugwawi_table_registry for database adapter

Revision ID: 023
Revises: 022_extend_crm_communication_links
Create Date: 2026-01-30

Creates a registry table that lists all HUGWAWI database tables with:
- position: Sequential number
- table_name: Name of the HUGWAWI table
- is_used_read: Whether this table is currently used for reading in the project
- remarks: User remarks/notes
- allow_write_production: Whether writing to production DB is allowed (default 0)
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '023'
down_revision = '022'
branch_labels = None
depends_on = None

# All HUGWAWI tables (231 tables)
ALL_HUGWAWI_TABLES = [
    "accounting_export",
    "accounting_list",
    "accounting_swift",
    "activitytype",
    "adrbase",
    "adrbase_number",
    "adrcont",
    "adrcont_email",
    "adrcont_emailtype",
    "adrcont_phone",
    "adrcont_phonetype",
    "adrconttype",
    "adrlimit",
    "adrlimit_status",
    "adrline",
    "adrline_account",
    "adrline_countries",
    "adrmline",
    "article",
    "article_attachment",
    "article_customer_priceinfo",
    "article_customfields",
    "article_distributor",
    "article_distributor_priceinfo",
    "article_distributor_qualification_rating",
    "article_generation",
    "article_materialgroup",
    "article_materialgroup_attachment",
    "article_materialgroup_field_label",
    "article_materialgroup_field_userrole",
    "article_priceinfo",
    "article_priceinfo_relation",
    "article_priceinfotype",
    "article_selectlist",
    "article_selectlist_value",
    "article_status",
    "article_stock",
    "article_stock_booking",
    "article_stock_booking_child",
    "attachment",
    "attachment_function",
    "attachment_userrole",
    "barcode_type",
    "billing_bank",
    "billing_bankaccount",
    "billing_client",
    "billing_costCenter",
    "billing_creditperiod",
    "billing_currency",
    "billing_customeraccount",
    "billing_customeraccount_status",
    "billing_deliveryNote",
    "billing_document",
    "billing_document_address",
    "billing_document_deliverynotenumber",
    "billing_document_pos",
    "billing_documenttype",
    "billing_factoring",
    "billing_interest_rate",
    "billing_invoice",
    "billing_mandant",
    "billing_mandant_makro",
    "billing_mandant_userlist",
    "billing_num",
    "billing_offer",
    "billing_orderDocumentType",
    "billing_packingconditions",
    "billing_porto",
    "billing_sales_rep",
    "billing_splitentry",
    "billing_tax",
    "billing_transactionType",
    "billing_type",
    "calculation",
    "calculation_copy",
    "calculation_materialgroup",
    "calculationtype",
    "CI",
    "constructionpoints",
    "countries",
    "crm_activity",
    "crm_activity_attachment",
    "crm_activity_recurring",
    "crm_activity_recurring_contact",
    "crm_activity_recurring_date",
    "crm_activity_recurring_date_contact",
    "crm_activity_recurring_resourceplan",
    "crm_activity_status",
    "crm_activity_topic",
    "crm_activity_type",
    "crm_contact_category",
    "crm_contact_category_relation",
    "crm_prospective",
    "crm_topic",
    "customer_account",
    "customer_time",
    "customerarticlenumbers",
    "danger_actions",
    "danger_area",
    "danger_group",
    "danger_risk",
    "dangeranalysis",
    "dangeranalysis_userlogin",
    "dangers",
    "datapoints",
    "deliveryannotation",
    "department",
    "dms_accessrights",
    "dms_accessrights_moveto",
    "dms_article",
    "dms_ci",
    "dms_config",
    "dms_customfields",
    "dms_document",
    "dms_document_autoload",
    "dms_document_folder",
    "dms_document_history",
    "dms_document_note",
    "dms_document_relation",
    "dms_documenttype",
    "dms_documenttype_customfieldlabel",
    "dms_documenttype_supportgroup",
    "dms_folder",
    "dms_folder_supportgroup",
    "dms_folder_template",
    "dms_import",
    "dms_lifecycle",
    "dms_lifecycle_supportgroup",
    "dms_note_type",
    "dms_order",
    "dms_type_orderdocument",
    "dms_workflow",
    "dms_workflow_accessrights",
    "dms_workflow_ar_moveto",
    "dms_workflow_supportgroup",
    "dunning",
    "emailhistory",
    "emailhistory_reference",
    "emailsender",
    "emailtemplate",
    "emailwildcards",
    "externalwork",
    "globalSettings",
    "grades",
    "hg_tooldatas",
    "incomingDeliveryNote",
    "incomingDeliveryNoteArticle",
    "invoice",
    "language",
    "machine",
    "mandant",
    "manufacturer",
    "menu",
    "menu_resources",
    "module_type",
    "ocupationtype_color",
    "opentime",
    "operator",
    "order_article",
    "order_article_booking",
    "order_article_booking_child",
    "order_article_chidlren_ref",
    "order_article_child_ref",
    "order_article_child_ref_copy",
    "order_article_children",
    "order_article_priceinfo",
    "order_article_ref",
    "order_article_ref_copy",
    "order_attachment",
    "order_bookingnumbers",
    "order_customer_adrline",
    "order_history",
    "order_number",
    "order_paymentplan",
    "order_recurring_invoicerun_invoice",
    "order_recurring_position",
    "order_status",
    "order_status_ups",
    "order_type",
    "orderfield",
    "orderfield_userrole",
    "ordertable",
    "ordertable_reference",
    "packingnote",
    "packingnote_calculation",
    "packingnote_details",
    "packingnote_field",
    "packingnote_gfl",
    "packingnote_relation",
    "pclconfig",
    "pclDocumentType",
    "pclLabelValue",
    "pdfConfig",
    "pdfConfigLanguage",
    "pdfCoord",
    "pdfFields",
    "portalau",
    "priceinfo_gfl",
    "printer",
    "publicholiday",
    "qualificationgroup",
    "qualificationitem",
    "qualificationitem_group",
    "qualificationitem_workstep",
    "reportlist",
    "reportlist_searchfields",
    "salutation",
    "selectlist",
    "selectlist_source",
    "selectlist_values",
    "servicetype",
    "sources",
    "splitaccounting",
    "staffmanagement",
    "staffmanagement_status",
    "staffmanagement_usertask",
    "stock",
    "stock_clearing",
    "stock_clearing_position",
    "stock_clearing_position_type",
    "stock_clearing_type",
    "stock_IncomingInvoices",
    "stock_IncomingInvoices_filter",
    "stock_payment",
    "stock_payment_entries",
    "stock_payment_type",
    "stock_serial",
    "supportgroup",
    "supportgroup_printer",
    "supportgroup_userlogin",
    "supportgroup_visible_supportgroups",
    "title",
    "toDo",
    "toDo_type",
    "training",
    "training_user",
    "ts_bool",
    "ts_counter",
    "ts_number",
    "ts_string",
    "ups_shipping_config",
    "ups_shipping_request",
    "ups_shipping_request_order_article",
    "ups_shipping_request_status",
    "ups_shipping_response",
    "user_info",
    "user_vacation",
    "user_workingtime_provision",
    "userlogin",
    "userlogin_clearingInfo",
    "userlogin_itemgroup",
    "userlogin_kid",
    "userlogin_printer_documenttype",
    "userlogin_qualification",
    "userlogin_userrole",
    "userprotocol",
    "userrole_provision",
    "userroles",
    "userroles_menu",
    "usertask",
    "usertask_overtime",
    "usertask_referenceorder",
    "welcometext",
    "workplan",
    "workplan_annotation",
    "workplan_configuration",
    "workplan_details",
    "workplan_history",
    "workplan_relation",
    "workplan_status",
    "workplan_times",
    "workplanimport",
    "workstep",
]

# Tables that are currently used for reading in the project (based on code analysis)
TABLES_USED_READ = {
    # Address/Contact tables
    "adrbase",
    "adrcont",
    "adrcont_email",
    "adrcont_phone",
    "adrconttype",
    "adrline",
    "adrline_account",
    # Article tables
    "article",
    "article_distributor",
    "article_materialgroup",
    "article_selectlist",
    "article_selectlist_value",
    "article_status",
    # Order tables
    "order_article",
    "order_article_ref",
    "order_status",
    "order_type",
    "ordertable",
    # Packingnote/BOM tables
    "packingnote_details",
    "packingnote_relation",
    # Workplan tables
    "workplan",
    "workplan_details",
    "workplan_relation",
    "workstep",
    # Qualification/Machine tables
    "qualificationitem",
    "qualificationitem_workstep",
    # User tables
    "department",
    "supportgroup_userlogin",
    "userlogin",
    "userlogin_userrole",
    "userroles",
    # Billing tables
    "billing_creditperiod",
    "billing_documenttype",
    "billing_factoring",
    "billing_packingconditions",
    # DMS tables
    "dms_article",
    "dms_config",
    "dms_document",
    "dms_document_history",
    "dms_document_note",
    "dms_documenttype",
    "dms_folder",
    "dms_order",
    "dms_workflow",
    "dms_workflow_accessrights",
    # Other tables
    "calculation",
    "incomingDeliveryNote",
    "incomingDeliveryNoteArticle",
    "language",
    "welcometext",
}


def upgrade():
    # Create the registry table
    op.create_table(
        'hugwawi_table_registry',
        sa.Column('position', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('table_name', sa.String(100), nullable=False),
        sa.Column('is_used_read', sa.Boolean(), nullable=False, default=False),
        sa.Column('remarks', sa.Text(), nullable=True),
        sa.Column('allow_write_production', sa.Boolean(), nullable=False, default=False),
        sa.PrimaryKeyConstraint('position'),
        sa.UniqueConstraint('table_name')
    )
    
    # Create index for faster lookups
    op.create_index(
        'idx_hugwawi_table_name',
        'hugwawi_table_registry',
        ['table_name'],
        unique=True
    )
    
    # Insert all HUGWAWI tables with is_used_read flag
    conn = op.get_bind()
    for table_name in ALL_HUGWAWI_TABLES:
        is_used = 1 if table_name in TABLES_USED_READ else 0
        conn.execute(
            sa.text(
                "INSERT INTO hugwawi_table_registry (table_name, is_used_read, allow_write_production) "
                "VALUES (:table_name, :is_used_read, 0)"
            ),
            {"table_name": table_name, "is_used_read": is_used}
        )


def downgrade():
    op.drop_index('idx_hugwawi_table_name', table_name='hugwawi_table_registry')
    op.drop_table('hugwawi_table_registry')
